<p>REGISTRO DE ORDEN DE COMPRA VIA INTRANET</p>
<p>SE ENCUENTRA EN MANTEMIENTO FAVOR DE REALIZAR SU OC MEDIANTE ESCRITORIO REMOTO</p>
<p>&nbsp;</p>
<p>ATTE.</p>
<p>&nbsp;</p>
<p>DPTO DE SISTEMAS.</p>
<p>TEL 6511974 ANEXO 206</p>
<p>&nbsp;</p>
